### ISSUE TITLE
How do you pass email and pass to your action auth ? 

### ISSUE THREAD

**Issue by rubensdemelo** [java-james/flutter_redux_boilerplate#1]
How do you pass email and pass to your action auth ?

**Comment by rubensdemelo** [comment]
Use action.myProperty

**Comment by java-james** [comment]
The middleware action can take arguments eg `onLogin(BuildContext context, String username, String password)`. Or were you referring to grabbing them from the form?

**Comment by rubensdemelo** [comment]
Grabbing them from the form. Im using like this: 

`store.dispach(LoginAction(email, password))`

On my middleware, to use parameters:

```
loginAction.email
loginAction.password
```

Is that a good approach ?
